spring.application.name=servesync-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/servesync?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=D2_89484_PRATHAMESH
spring.datasource.password=manager

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=8080

# JWT Secret (for JWT-based auth)
jwt.secret=e9f3d0604bf84a3e24553bb289886bf24bbc9eb6d099c0d6ced0814c1aad4bf96c39260867789a5502bfd6ab73241035983a4c76de3d82674d74106d3adf3d49
jwt.expiration=86400000
jwt.token-prefix=Bearer
jwt.signature-algorithm=HS256
auth.default-role=ROLE_CUSTOMER
